/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.19.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

namespace Zaap
{
  public partial class ZaapService
  {
    public interface IAsync
    {
      global::System.Threading.Tasks.Task<string> @connect(string gameName, string releaseName, int instanceId, string @hash, CancellationToken cancellationToken = default);

      global::System.Threading.Tasks.Task<string> auth_getGameToken(string gameSession, int gameId, CancellationToken cancellationToken = default);

      global::System.Threading.Tasks.Task<string> settings_get(string gameSession, string @key, CancellationToken cancellationToken = default);

      global::System.Threading.Tasks.Task<string> userInfo_get(string gameSession, CancellationToken cancellationToken = default);

      global::System.Threading.Tasks.Task<string> updater_isUpdateAvailable(string gameSession, CancellationToken cancellationToken = default);

    }


    public class Client : TBaseClient, IDisposable, IAsync
    {
      public Client(TProtocol protocol) : this(protocol, protocol)
      {
      }

      public Client(TProtocol inputProtocol, TProtocol outputProtocol) : base(inputProtocol, outputProtocol)
      {
      }

      public async global::System.Threading.Tasks.Task<string> @connect(string gameName, string releaseName, int instanceId, string @hash, CancellationToken cancellationToken = default)
      {
        await send_connect(gameName, releaseName, instanceId, @hash, cancellationToken);
        return await recv_connect(cancellationToken);
      }

      public async global::System.Threading.Tasks.Task send_connect(string gameName, string releaseName, int instanceId, string @hash, CancellationToken cancellationToken = default)
      {
        await OutputProtocol.WriteMessageBeginAsync(new TMessage("connect", TMessageType.Call, SeqId), cancellationToken);
        
        var tmp0 = new InternalStructs.connect_args() {
          GameName = gameName,
          ReleaseName = releaseName,
          InstanceId = instanceId,
          Hash = @hash,
        };
        
        await tmp0.WriteAsync(OutputProtocol, cancellationToken);
        await OutputProtocol.WriteMessageEndAsync(cancellationToken);
        await OutputProtocol.Transport.FlushAsync(cancellationToken);
      }

      public async global::System.Threading.Tasks.Task<string> recv_connect(CancellationToken cancellationToken = default)
      {
        
        var tmp1 = await InputProtocol.ReadMessageBeginAsync(cancellationToken);
        if (tmp1.Type == TMessageType.Exception)
        {
          var tmp2 = await TApplicationException.ReadAsync(InputProtocol, cancellationToken);
          await InputProtocol.ReadMessageEndAsync(cancellationToken);
          throw tmp2;
        }

        var tmp3 = new InternalStructs.connect_result();
        await tmp3.ReadAsync(InputProtocol, cancellationToken);
        await InputProtocol.ReadMessageEndAsync(cancellationToken);
        if (tmp3.__isset.success)
        {
          return tmp3.Success;
        }
        throw new TApplicationException(TApplicationException.ExceptionType.MissingResult, "connect failed: unknown result");
      }

      public async global::System.Threading.Tasks.Task<string> auth_getGameToken(string gameSession, int gameId, CancellationToken cancellationToken = default)
      {
        await send_auth_getGameToken(gameSession, gameId, cancellationToken);
        return await recv_auth_getGameToken(cancellationToken);
      }

      public async global::System.Threading.Tasks.Task send_auth_getGameToken(string gameSession, int gameId, CancellationToken cancellationToken = default)
      {
        await OutputProtocol.WriteMessageBeginAsync(new TMessage("auth_getGameToken", TMessageType.Call, SeqId), cancellationToken);
        
        var tmp4 = new InternalStructs.auth_getGameToken_args() {
          GameSession = gameSession,
          GameId = gameId,
        };
        
        await tmp4.WriteAsync(OutputProtocol, cancellationToken);
        await OutputProtocol.WriteMessageEndAsync(cancellationToken);
        await OutputProtocol.Transport.FlushAsync(cancellationToken);
      }

      public async global::System.Threading.Tasks.Task<string> recv_auth_getGameToken(CancellationToken cancellationToken = default)
      {
        
        var tmp5 = await InputProtocol.ReadMessageBeginAsync(cancellationToken);
        if (tmp5.Type == TMessageType.Exception)
        {
          var tmp6 = await TApplicationException.ReadAsync(InputProtocol, cancellationToken);
          await InputProtocol.ReadMessageEndAsync(cancellationToken);
          throw tmp6;
        }

        var tmp7 = new InternalStructs.auth_getGameToken_result();
        await tmp7.ReadAsync(InputProtocol, cancellationToken);
        await InputProtocol.ReadMessageEndAsync(cancellationToken);
        if (tmp7.__isset.success)
        {
          return tmp7.Success;
        }
        throw new TApplicationException(TApplicationException.ExceptionType.MissingResult, "auth_getGameToken failed: unknown result");
      }

      public async global::System.Threading.Tasks.Task<string> settings_get(string gameSession, string @key, CancellationToken cancellationToken = default)
      {
        await send_settings_get(gameSession, @key, cancellationToken);
        return await recv_settings_get(cancellationToken);
      }

      public async global::System.Threading.Tasks.Task send_settings_get(string gameSession, string @key, CancellationToken cancellationToken = default)
      {
        await OutputProtocol.WriteMessageBeginAsync(new TMessage("settings_get", TMessageType.Call, SeqId), cancellationToken);
        
        var tmp8 = new InternalStructs.settings_get_args() {
          GameSession = gameSession,
          Key = @key,
        };
        
        await tmp8.WriteAsync(OutputProtocol, cancellationToken);
        await OutputProtocol.WriteMessageEndAsync(cancellationToken);
        await OutputProtocol.Transport.FlushAsync(cancellationToken);
      }

      public async global::System.Threading.Tasks.Task<string> recv_settings_get(CancellationToken cancellationToken = default)
      {
        
        var tmp9 = await InputProtocol.ReadMessageBeginAsync(cancellationToken);
        if (tmp9.Type == TMessageType.Exception)
        {
          var tmp10 = await TApplicationException.ReadAsync(InputProtocol, cancellationToken);
          await InputProtocol.ReadMessageEndAsync(cancellationToken);
          throw tmp10;
        }

        var tmp11 = new InternalStructs.settings_get_result();
        await tmp11.ReadAsync(InputProtocol, cancellationToken);
        await InputProtocol.ReadMessageEndAsync(cancellationToken);
        if (tmp11.__isset.success)
        {
          return tmp11.Success;
        }
        throw new TApplicationException(TApplicationException.ExceptionType.MissingResult, "settings_get failed: unknown result");
      }

      public async global::System.Threading.Tasks.Task<string> userInfo_get(string gameSession, CancellationToken cancellationToken = default)
      {
        await send_userInfo_get(gameSession, cancellationToken);
        return await recv_userInfo_get(cancellationToken);
      }

      public async global::System.Threading.Tasks.Task send_userInfo_get(string gameSession, CancellationToken cancellationToken = default)
      {
        await OutputProtocol.WriteMessageBeginAsync(new TMessage("userInfo_get", TMessageType.Call, SeqId), cancellationToken);
        
        var tmp12 = new InternalStructs.userInfo_get_args() {
          GameSession = gameSession,
        };
        
        await tmp12.WriteAsync(OutputProtocol, cancellationToken);
        await OutputProtocol.WriteMessageEndAsync(cancellationToken);
        await OutputProtocol.Transport.FlushAsync(cancellationToken);
      }

      public async global::System.Threading.Tasks.Task<string> recv_userInfo_get(CancellationToken cancellationToken = default)
      {
        
        var tmp13 = await InputProtocol.ReadMessageBeginAsync(cancellationToken);
        if (tmp13.Type == TMessageType.Exception)
        {
          var tmp14 = await TApplicationException.ReadAsync(InputProtocol, cancellationToken);
          await InputProtocol.ReadMessageEndAsync(cancellationToken);
          throw tmp14;
        }

        var tmp15 = new InternalStructs.userInfo_get_result();
        await tmp15.ReadAsync(InputProtocol, cancellationToken);
        await InputProtocol.ReadMessageEndAsync(cancellationToken);
        if (tmp15.__isset.success)
        {
          return tmp15.Success;
        }
        throw new TApplicationException(TApplicationException.ExceptionType.MissingResult, "userInfo_get failed: unknown result");
      }

      public async global::System.Threading.Tasks.Task<string> updater_isUpdateAvailable(string gameSession, CancellationToken cancellationToken = default)
      {
        await send_updater_isUpdateAvailable(gameSession, cancellationToken);
        return await recv_updater_isUpdateAvailable(cancellationToken);
      }

      public async global::System.Threading.Tasks.Task send_updater_isUpdateAvailable(string gameSession, CancellationToken cancellationToken = default)
      {
        await OutputProtocol.WriteMessageBeginAsync(new TMessage("updater_isUpdateAvailable", TMessageType.Call, SeqId), cancellationToken);
        
        var tmp16 = new InternalStructs.updater_isUpdateAvailable_args() {
          GameSession = gameSession,
        };
        
        await tmp16.WriteAsync(OutputProtocol, cancellationToken);
        await OutputProtocol.WriteMessageEndAsync(cancellationToken);
        await OutputProtocol.Transport.FlushAsync(cancellationToken);
      }

      public async global::System.Threading.Tasks.Task<string> recv_updater_isUpdateAvailable(CancellationToken cancellationToken = default)
      {
        
        var tmp17 = await InputProtocol.ReadMessageBeginAsync(cancellationToken);
        if (tmp17.Type == TMessageType.Exception)
        {
          var tmp18 = await TApplicationException.ReadAsync(InputProtocol, cancellationToken);
          await InputProtocol.ReadMessageEndAsync(cancellationToken);
          throw tmp18;
        }

        var tmp19 = new InternalStructs.updater_isUpdateAvailable_result();
        await tmp19.ReadAsync(InputProtocol, cancellationToken);
        await InputProtocol.ReadMessageEndAsync(cancellationToken);
        if (tmp19.__isset.success)
        {
          return tmp19.Success;
        }
        throw new TApplicationException(TApplicationException.ExceptionType.MissingResult, "updater_isUpdateAvailable failed: unknown result");
      }

    }

    public class AsyncProcessor : ITAsyncProcessor
    {
      private readonly IAsync _iAsync;
      private readonly ILogger<AsyncProcessor> _logger;

      public AsyncProcessor(IAsync iAsync, ILogger<AsyncProcessor> logger = default)
      {
        _iAsync = iAsync ?? throw new ArgumentNullException(nameof(iAsync));
        _logger = logger;
        processMap_["connect"] = connect_ProcessAsync;
        processMap_["auth_getGameToken"] = auth_getGameToken_ProcessAsync;
        processMap_["settings_get"] = settings_get_ProcessAsync;
        processMap_["userInfo_get"] = userInfo_get_ProcessAsync;
        processMap_["updater_isUpdateAvailable"] = updater_isUpdateAvailable_ProcessAsync;
      }

      protected delegate global::System.Threading.Tasks.Task ProcessFunction(int seqid, TProtocol iprot, TProtocol oprot, CancellationToken cancellationToken);
      protected Dictionary<string, ProcessFunction> processMap_ = new Dictionary<string, ProcessFunction>();

      public async Task<bool> ProcessAsync(TProtocol iprot, TProtocol oprot)
      {
        return await ProcessAsync(iprot, oprot, CancellationToken.None);
      }

      public async Task<bool> ProcessAsync(TProtocol iprot, TProtocol oprot, CancellationToken cancellationToken)
      {
        try
        {
          var msg = await iprot.ReadMessageBeginAsync(cancellationToken);

          processMap_.TryGetValue(msg.Name, out var fn);

          if (fn == null)
          {
            await TProtocolUtil.SkipAsync(iprot, TType.Struct, cancellationToken);
            await iprot.ReadMessageEndAsync(cancellationToken);
            var x = new TApplicationException (TApplicationException.ExceptionType.UnknownMethod, "Invalid method name: '" + msg.Name + "'");
            await oprot.WriteMessageBeginAsync(new TMessage(msg.Name, TMessageType.Exception, msg.SeqID), cancellationToken);
            await x.WriteAsync(oprot, cancellationToken);
            await oprot.WriteMessageEndAsync(cancellationToken);
            await oprot.Transport.FlushAsync(cancellationToken);
            return true;
          }

          await fn(msg.SeqID, iprot, oprot, cancellationToken);

        }
        catch (IOException)
        {
          return false;
        }

        return true;
      }

      public async global::System.Threading.Tasks.Task connect_ProcessAsync(int seqid, TProtocol iprot, TProtocol oprot, CancellationToken cancellationToken)
      {
        var tmp20 = new InternalStructs.connect_args();
        await tmp20.ReadAsync(iprot, cancellationToken);
        await iprot.ReadMessageEndAsync(cancellationToken);
        var tmp21 = new InternalStructs.connect_result();
        try
        {
          tmp21.Success = await _iAsync.@connect(tmp20.GameName, tmp20.ReleaseName, tmp20.InstanceId, tmp20.Hash, cancellationToken);
          await oprot.WriteMessageBeginAsync(new TMessage("connect", TMessageType.Reply, seqid), cancellationToken); 
          await tmp21.WriteAsync(oprot, cancellationToken);
        }
        catch (TTransportException)
        {
          throw;
        }
        catch (Exception tmp22)
        {
          var tmp23 = $"Error occurred in {GetType().FullName}: {tmp22.Message}";
          if(_logger != null)
            _logger.LogError("{Exception}, {Message}", tmp22, tmp23);
          else
            Console.Error.WriteLine(tmp23);
          var tmp24 = new TApplicationException(TApplicationException.ExceptionType.InternalError," Internal error.");
          await oprot.WriteMessageBeginAsync(new TMessage("connect", TMessageType.Exception, seqid), cancellationToken);
          await tmp24.WriteAsync(oprot, cancellationToken);
        }
        await oprot.WriteMessageEndAsync(cancellationToken);
        await oprot.Transport.FlushAsync(cancellationToken);
      }

      public async global::System.Threading.Tasks.Task auth_getGameToken_ProcessAsync(int seqid, TProtocol iprot, TProtocol oprot, CancellationToken cancellationToken)
      {
        var tmp25 = new InternalStructs.auth_getGameToken_args();
        await tmp25.ReadAsync(iprot, cancellationToken);
        await iprot.ReadMessageEndAsync(cancellationToken);
        var tmp26 = new InternalStructs.auth_getGameToken_result();
        try
        {
          tmp26.Success = await _iAsync.auth_getGameToken(tmp25.GameSession, tmp25.GameId, cancellationToken);
          await oprot.WriteMessageBeginAsync(new TMessage("auth_getGameToken", TMessageType.Reply, seqid), cancellationToken); 
          await tmp26.WriteAsync(oprot, cancellationToken);
        }
        catch (TTransportException)
        {
          throw;
        }
        catch (Exception tmp27)
        {
          var tmp28 = $"Error occurred in {GetType().FullName}: {tmp27.Message}";
          if(_logger != null)
            _logger.LogError("{Exception}, {Message}", tmp27, tmp28);
          else
            Console.Error.WriteLine(tmp28);
          var tmp29 = new TApplicationException(TApplicationException.ExceptionType.InternalError," Internal error.");
          await oprot.WriteMessageBeginAsync(new TMessage("auth_getGameToken", TMessageType.Exception, seqid), cancellationToken);
          await tmp29.WriteAsync(oprot, cancellationToken);
        }
        await oprot.WriteMessageEndAsync(cancellationToken);
        await oprot.Transport.FlushAsync(cancellationToken);
      }

      public async global::System.Threading.Tasks.Task settings_get_ProcessAsync(int seqid, TProtocol iprot, TProtocol oprot, CancellationToken cancellationToken)
      {
        var tmp30 = new InternalStructs.settings_get_args();
        await tmp30.ReadAsync(iprot, cancellationToken);
        await iprot.ReadMessageEndAsync(cancellationToken);
        var tmp31 = new InternalStructs.settings_get_result();
        try
        {
          tmp31.Success = await _iAsync.settings_get(tmp30.GameSession, tmp30.Key, cancellationToken);
          await oprot.WriteMessageBeginAsync(new TMessage("settings_get", TMessageType.Reply, seqid), cancellationToken); 
          await tmp31.WriteAsync(oprot, cancellationToken);
        }
        catch (TTransportException)
        {
          throw;
        }
        catch (Exception tmp32)
        {
          var tmp33 = $"Error occurred in {GetType().FullName}: {tmp32.Message}";
          if(_logger != null)
            _logger.LogError("{Exception}, {Message}", tmp32, tmp33);
          else
            Console.Error.WriteLine(tmp33);
          var tmp34 = new TApplicationException(TApplicationException.ExceptionType.InternalError," Internal error.");
          await oprot.WriteMessageBeginAsync(new TMessage("settings_get", TMessageType.Exception, seqid), cancellationToken);
          await tmp34.WriteAsync(oprot, cancellationToken);
        }
        await oprot.WriteMessageEndAsync(cancellationToken);
        await oprot.Transport.FlushAsync(cancellationToken);
      }

      public async global::System.Threading.Tasks.Task userInfo_get_ProcessAsync(int seqid, TProtocol iprot, TProtocol oprot, CancellationToken cancellationToken)
      {
        var tmp35 = new InternalStructs.userInfo_get_args();
        await tmp35.ReadAsync(iprot, cancellationToken);
        await iprot.ReadMessageEndAsync(cancellationToken);
        var tmp36 = new InternalStructs.userInfo_get_result();
        try
        {
          tmp36.Success = await _iAsync.userInfo_get(tmp35.GameSession, cancellationToken);
          await oprot.WriteMessageBeginAsync(new TMessage("userInfo_get", TMessageType.Reply, seqid), cancellationToken); 
          await tmp36.WriteAsync(oprot, cancellationToken);
        }
        catch (TTransportException)
        {
          throw;
        }
        catch (Exception tmp37)
        {
          var tmp38 = $"Error occurred in {GetType().FullName}: {tmp37.Message}";
          if(_logger != null)
            _logger.LogError("{Exception}, {Message}", tmp37, tmp38);
          else
            Console.Error.WriteLine(tmp38);
          var tmp39 = new TApplicationException(TApplicationException.ExceptionType.InternalError," Internal error.");
          await oprot.WriteMessageBeginAsync(new TMessage("userInfo_get", TMessageType.Exception, seqid), cancellationToken);
          await tmp39.WriteAsync(oprot, cancellationToken);
        }
        await oprot.WriteMessageEndAsync(cancellationToken);
        await oprot.Transport.FlushAsync(cancellationToken);
      }

      public async global::System.Threading.Tasks.Task updater_isUpdateAvailable_ProcessAsync(int seqid, TProtocol iprot, TProtocol oprot, CancellationToken cancellationToken)
      {
        var tmp40 = new InternalStructs.updater_isUpdateAvailable_args();
        await tmp40.ReadAsync(iprot, cancellationToken);
        await iprot.ReadMessageEndAsync(cancellationToken);
        var tmp41 = new InternalStructs.updater_isUpdateAvailable_result();
        try
        {
          tmp41.Success = await _iAsync.updater_isUpdateAvailable(tmp40.GameSession, cancellationToken);
          await oprot.WriteMessageBeginAsync(new TMessage("updater_isUpdateAvailable", TMessageType.Reply, seqid), cancellationToken); 
          await tmp41.WriteAsync(oprot, cancellationToken);
        }
        catch (TTransportException)
        {
          throw;
        }
        catch (Exception tmp42)
        {
          var tmp43 = $"Error occurred in {GetType().FullName}: {tmp42.Message}";
          if(_logger != null)
            _logger.LogError("{Exception}, {Message}", tmp42, tmp43);
          else
            Console.Error.WriteLine(tmp43);
          var tmp44 = new TApplicationException(TApplicationException.ExceptionType.InternalError," Internal error.");
          await oprot.WriteMessageBeginAsync(new TMessage("updater_isUpdateAvailable", TMessageType.Exception, seqid), cancellationToken);
          await tmp44.WriteAsync(oprot, cancellationToken);
        }
        await oprot.WriteMessageEndAsync(cancellationToken);
        await oprot.Transport.FlushAsync(cancellationToken);
      }

    }

    public class InternalStructs
    {

      public partial class connect_args : TBase
      {
        private string _gameName;
        private string _releaseName;
        private int _instanceId;
        private string _hash;

        public string GameName
        {
          get
          {
            return _gameName;
          }
          set
          {
            __isset.gameName = true;
            this._gameName = value;
          }
        }

        public string ReleaseName
        {
          get
          {
            return _releaseName;
          }
          set
          {
            __isset.releaseName = true;
            this._releaseName = value;
          }
        }

        public int InstanceId
        {
          get
          {
            return _instanceId;
          }
          set
          {
            __isset.instanceId = true;
            this._instanceId = value;
          }
        }

        public string Hash
        {
          get
          {
            return _hash;
          }
          set
          {
            __isset.@hash = true;
            this._hash = value;
          }
        }


        public Isset __isset;
        public struct Isset
        {
          public bool gameName;
          public bool releaseName;
          public bool instanceId;
          public bool @hash;
        }

        public connect_args()
        {
        }

        public connect_args DeepCopy()
        {
          var tmp45 = new connect_args();
          if((GameName != null) && __isset.gameName)
          {
            tmp45.GameName = this.GameName;
          }
          tmp45.__isset.gameName = this.__isset.gameName;
          if((ReleaseName != null) && __isset.releaseName)
          {
            tmp45.ReleaseName = this.ReleaseName;
          }
          tmp45.__isset.releaseName = this.__isset.releaseName;
          if(__isset.instanceId)
          {
            tmp45.InstanceId = this.InstanceId;
          }
          tmp45.__isset.instanceId = this.__isset.instanceId;
          if((Hash != null) && __isset.@hash)
          {
            tmp45.Hash = this.Hash;
          }
          tmp45.__isset.@hash = this.__isset.@hash;
          return tmp45;
        }

        public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
        {
          iprot.IncrementRecursionDepth();
          try
          {
            TField field;
            await iprot.ReadStructBeginAsync(cancellationToken);
            while (true)
            {
              field = await iprot.ReadFieldBeginAsync(cancellationToken);
              if (field.Type == TType.Stop)
              {
                break;
              }

              switch (field.ID)
              {
                case 1:
                  if (field.Type == TType.String)
                  {
                    GameName = await iprot.ReadStringAsync(cancellationToken);
                  }
                  else
                  {
                    await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                  }
                  break;
                case 2:
                  if (field.Type == TType.String)
                  {
                    ReleaseName = await iprot.ReadStringAsync(cancellationToken);
                  }
                  else
                  {
                    await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                  }
                  break;
                case 3:
                  if (field.Type == TType.I32)
                  {
                    InstanceId = await iprot.ReadI32Async(cancellationToken);
                  }
                  else
                  {
                    await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                  }
                  break;
                case 4:
                  if (field.Type == TType.String)
                  {
                    Hash = await iprot.ReadStringAsync(cancellationToken);
                  }
                  else
                  {
                    await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                  }
                  break;
                default: 
                  await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                  break;
              }

              await iprot.ReadFieldEndAsync(cancellationToken);
            }

            await iprot.ReadStructEndAsync(cancellationToken);
          }
          finally
          {
            iprot.DecrementRecursionDepth();
          }
        }

        public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
        {
          oprot.IncrementRecursionDepth();
          try
          {
            var tmp46 = new TStruct("connect_args");
            await oprot.WriteStructBeginAsync(tmp46, cancellationToken);
            var tmp47 = new TField();
            if((GameName != null) && __isset.gameName)
            {
              tmp47.Name = "gameName";
              tmp47.Type = TType.String;
              tmp47.ID = 1;
              await oprot.WriteFieldBeginAsync(tmp47, cancellationToken);
              await oprot.WriteStringAsync(GameName, cancellationToken);
              await oprot.WriteFieldEndAsync(cancellationToken);
            }
            if((ReleaseName != null) && __isset.releaseName)
            {
              tmp47.Name = "releaseName";
              tmp47.Type = TType.String;
              tmp47.ID = 2;
              await oprot.WriteFieldBeginAsync(tmp47, cancellationToken);
              await oprot.WriteStringAsync(ReleaseName, cancellationToken);
              await oprot.WriteFieldEndAsync(cancellationToken);
            }
            if(__isset.instanceId)
            {
              tmp47.Name = "instanceId";
              tmp47.Type = TType.I32;
              tmp47.ID = 3;
              await oprot.WriteFieldBeginAsync(tmp47, cancellationToken);
              await oprot.WriteI32Async(InstanceId, cancellationToken);
              await oprot.WriteFieldEndAsync(cancellationToken);
            }
            if((Hash != null) && __isset.@hash)
            {
              tmp47.Name = "hash";
              tmp47.Type = TType.String;
              tmp47.ID = 4;
              await oprot.WriteFieldBeginAsync(tmp47, cancellationToken);
              await oprot.WriteStringAsync(Hash, cancellationToken);
              await oprot.WriteFieldEndAsync(cancellationToken);
            }
            await oprot.WriteFieldStopAsync(cancellationToken);
            await oprot.WriteStructEndAsync(cancellationToken);
          }
          finally
          {
            oprot.DecrementRecursionDepth();
          }
        }

        public override bool Equals(object that)
        {
          if (!(that is connect_args other)) return false;
          if (ReferenceEquals(this, other)) return true;
          return ((__isset.gameName == other.__isset.gameName) && ((!__isset.gameName) || (global::System.Object.Equals(GameName, other.GameName))))
            && ((__isset.releaseName == other.__isset.releaseName) && ((!__isset.releaseName) || (global::System.Object.Equals(ReleaseName, other.ReleaseName))))
            && ((__isset.instanceId == other.__isset.instanceId) && ((!__isset.instanceId) || (global::System.Object.Equals(InstanceId, other.InstanceId))))
            && ((__isset.@hash == other.__isset.@hash) && ((!__isset.@hash) || (global::System.Object.Equals(Hash, other.Hash))));
        }

        public override int GetHashCode() {
          int hashcode = 157;
          unchecked {
            if((GameName != null) && __isset.gameName)
            {
              hashcode = (hashcode * 397) + GameName.GetHashCode();
            }
            if((ReleaseName != null) && __isset.releaseName)
            {
              hashcode = (hashcode * 397) + ReleaseName.GetHashCode();
            }
            if(__isset.instanceId)
            {
              hashcode = (hashcode * 397) + InstanceId.GetHashCode();
            }
            if((Hash != null) && __isset.@hash)
            {
              hashcode = (hashcode * 397) + Hash.GetHashCode();
            }
          }
          return hashcode;
        }

        public override string ToString()
        {
          var tmp48 = new StringBuilder("connect_args(");
          int tmp49 = 0;
          if((GameName != null) && __isset.gameName)
          {
            if(0 < tmp49++) { tmp48.Append(", "); }
            tmp48.Append("GameName: ");
            GameName.ToString(tmp48);
          }
          if((ReleaseName != null) && __isset.releaseName)
          {
            if(0 < tmp49++) { tmp48.Append(", "); }
            tmp48.Append("ReleaseName: ");
            ReleaseName.ToString(tmp48);
          }
          if(__isset.instanceId)
          {
            if(0 < tmp49++) { tmp48.Append(", "); }
            tmp48.Append("InstanceId: ");
            InstanceId.ToString(tmp48);
          }
          if((Hash != null) && __isset.@hash)
          {
            if(0 < tmp49++) { tmp48.Append(", "); }
            tmp48.Append("Hash: ");
            Hash.ToString(tmp48);
          }
          tmp48.Append(')');
          return tmp48.ToString();
        }
      }


      public partial class connect_result : TBase
      {
        private string _success;

        public string Success
        {
          get
          {
            return _success;
          }
          set
          {
            __isset.@success = true;
            this._success = value;
          }
        }


        public Isset __isset;
        public struct Isset
        {
          public bool @success;
        }

        public connect_result()
        {
        }

        public connect_result DeepCopy()
        {
          var tmp50 = new connect_result();
          if((Success != null) && __isset.@success)
          {
            tmp50.Success = this.Success;
          }
          tmp50.__isset.@success = this.__isset.@success;
          return tmp50;
        }

        public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
        {
          iprot.IncrementRecursionDepth();
          try
          {
            TField field;
            await iprot.ReadStructBeginAsync(cancellationToken);
            while (true)
            {
              field = await iprot.ReadFieldBeginAsync(cancellationToken);
              if (field.Type == TType.Stop)
              {
                break;
              }

              switch (field.ID)
              {
                case 0:
                  if (field.Type == TType.String)
                  {
                    Success = await iprot.ReadStringAsync(cancellationToken);
                  }
                  else
                  {
                    await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                  }
                  break;
                default: 
                  await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                  break;
              }

              await iprot.ReadFieldEndAsync(cancellationToken);
            }

            await iprot.ReadStructEndAsync(cancellationToken);
          }
          finally
          {
            iprot.DecrementRecursionDepth();
          }
        }

        public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
        {
          oprot.IncrementRecursionDepth();
          try
          {
            var tmp51 = new TStruct("connect_result");
            await oprot.WriteStructBeginAsync(tmp51, cancellationToken);
            var tmp52 = new TField();

            if(this.__isset.@success)
            {
              if (Success != null)
              {
                tmp52.Name = "Success";
                tmp52.Type = TType.String;
                tmp52.ID = 0;
                await oprot.WriteFieldBeginAsync(tmp52, cancellationToken);
                await oprot.WriteStringAsync(Success, cancellationToken);
                await oprot.WriteFieldEndAsync(cancellationToken);
              }
            }
            await oprot.WriteFieldStopAsync(cancellationToken);
            await oprot.WriteStructEndAsync(cancellationToken);
          }
          finally
          {
            oprot.DecrementRecursionDepth();
          }
        }

        public override bool Equals(object that)
        {
          if (!(that is connect_result other)) return false;
          if (ReferenceEquals(this, other)) return true;
          return ((__isset.@success == other.__isset.@success) && ((!__isset.@success) || (global::System.Object.Equals(Success, other.Success))));
        }

        public override int GetHashCode() {
          int hashcode = 157;
          unchecked {
            if((Success != null) && __isset.@success)
            {
              hashcode = (hashcode * 397) + Success.GetHashCode();
            }
          }
          return hashcode;
        }

        public override string ToString()
        {
          var tmp53 = new StringBuilder("connect_result(");
          int tmp54 = 0;
          if((Success != null) && __isset.@success)
          {
            if(0 < tmp54++) { tmp53.Append(", "); }
            tmp53.Append("Success: ");
            Success.ToString(tmp53);
          }
          tmp53.Append(')');
          return tmp53.ToString();
        }
      }


      public partial class auth_getGameToken_args : TBase
      {
        private string _gameSession;
        private int _gameId;

        public string GameSession
        {
          get
          {
            return _gameSession;
          }
          set
          {
            __isset.gameSession = true;
            this._gameSession = value;
          }
        }

        public int GameId
        {
          get
          {
            return _gameId;
          }
          set
          {
            __isset.gameId = true;
            this._gameId = value;
          }
        }


        public Isset __isset;
        public struct Isset
        {
          public bool gameSession;
          public bool gameId;
        }

        public auth_getGameToken_args()
        {
        }

        public auth_getGameToken_args DeepCopy()
        {
          var tmp55 = new auth_getGameToken_args();
          if((GameSession != null) && __isset.gameSession)
          {
            tmp55.GameSession = this.GameSession;
          }
          tmp55.__isset.gameSession = this.__isset.gameSession;
          if(__isset.gameId)
          {
            tmp55.GameId = this.GameId;
          }
          tmp55.__isset.gameId = this.__isset.gameId;
          return tmp55;
        }

        public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
        {
          iprot.IncrementRecursionDepth();
          try
          {
            TField field;
            await iprot.ReadStructBeginAsync(cancellationToken);
            while (true)
            {
              field = await iprot.ReadFieldBeginAsync(cancellationToken);
              if (field.Type == TType.Stop)
              {
                break;
              }

              switch (field.ID)
              {
                case 1:
                  if (field.Type == TType.String)
                  {
                    GameSession = await iprot.ReadStringAsync(cancellationToken);
                  }
                  else
                  {
                    await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                  }
                  break;
                case 2:
                  if (field.Type == TType.I32)
                  {
                    GameId = await iprot.ReadI32Async(cancellationToken);
                  }
                  else
                  {
                    await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                  }
                  break;
                default: 
                  await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                  break;
              }

              await iprot.ReadFieldEndAsync(cancellationToken);
            }

            await iprot.ReadStructEndAsync(cancellationToken);
          }
          finally
          {
            iprot.DecrementRecursionDepth();
          }
        }

        public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
        {
          oprot.IncrementRecursionDepth();
          try
          {
            var tmp56 = new TStruct("auth_getGameToken_args");
            await oprot.WriteStructBeginAsync(tmp56, cancellationToken);
            var tmp57 = new TField();
            if((GameSession != null) && __isset.gameSession)
            {
              tmp57.Name = "gameSession";
              tmp57.Type = TType.String;
              tmp57.ID = 1;
              await oprot.WriteFieldBeginAsync(tmp57, cancellationToken);
              await oprot.WriteStringAsync(GameSession, cancellationToken);
              await oprot.WriteFieldEndAsync(cancellationToken);
            }
            if(__isset.gameId)
            {
              tmp57.Name = "gameId";
              tmp57.Type = TType.I32;
              tmp57.ID = 2;
              await oprot.WriteFieldBeginAsync(tmp57, cancellationToken);
              await oprot.WriteI32Async(GameId, cancellationToken);
              await oprot.WriteFieldEndAsync(cancellationToken);
            }
            await oprot.WriteFieldStopAsync(cancellationToken);
            await oprot.WriteStructEndAsync(cancellationToken);
          }
          finally
          {
            oprot.DecrementRecursionDepth();
          }
        }

        public override bool Equals(object that)
        {
          if (!(that is auth_getGameToken_args other)) return false;
          if (ReferenceEquals(this, other)) return true;
          return ((__isset.gameSession == other.__isset.gameSession) && ((!__isset.gameSession) || (global::System.Object.Equals(GameSession, other.GameSession))))
            && ((__isset.gameId == other.__isset.gameId) && ((!__isset.gameId) || (global::System.Object.Equals(GameId, other.GameId))));
        }

        public override int GetHashCode() {
          int hashcode = 157;
          unchecked {
            if((GameSession != null) && __isset.gameSession)
            {
              hashcode = (hashcode * 397) + GameSession.GetHashCode();
            }
            if(__isset.gameId)
            {
              hashcode = (hashcode * 397) + GameId.GetHashCode();
            }
          }
          return hashcode;
        }

        public override string ToString()
        {
          var tmp58 = new StringBuilder("auth_getGameToken_args(");
          int tmp59 = 0;
          if((GameSession != null) && __isset.gameSession)
          {
            if(0 < tmp59++) { tmp58.Append(", "); }
            tmp58.Append("GameSession: ");
            GameSession.ToString(tmp58);
          }
          if(__isset.gameId)
          {
            if(0 < tmp59++) { tmp58.Append(", "); }
            tmp58.Append("GameId: ");
            GameId.ToString(tmp58);
          }
          tmp58.Append(')');
          return tmp58.ToString();
        }
      }


      public partial class auth_getGameToken_result : TBase
      {
        private string _success;

        public string Success
        {
          get
          {
            return _success;
          }
          set
          {
            __isset.@success = true;
            this._success = value;
          }
        }


        public Isset __isset;
        public struct Isset
        {
          public bool @success;
        }

        public auth_getGameToken_result()
        {
        }

        public auth_getGameToken_result DeepCopy()
        {
          var tmp60 = new auth_getGameToken_result();
          if((Success != null) && __isset.@success)
          {
            tmp60.Success = this.Success;
          }
          tmp60.__isset.@success = this.__isset.@success;
          return tmp60;
        }

        public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
        {
          iprot.IncrementRecursionDepth();
          try
          {
            TField field;
            await iprot.ReadStructBeginAsync(cancellationToken);
            while (true)
            {
              field = await iprot.ReadFieldBeginAsync(cancellationToken);
              if (field.Type == TType.Stop)
              {
                break;
              }

              switch (field.ID)
              {
                case 0:
                  if (field.Type == TType.String)
                  {
                    Success = await iprot.ReadStringAsync(cancellationToken);
                  }
                  else
                  {
                    await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                  }
                  break;
                default: 
                  await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                  break;
              }

              await iprot.ReadFieldEndAsync(cancellationToken);
            }

            await iprot.ReadStructEndAsync(cancellationToken);
          }
          finally
          {
            iprot.DecrementRecursionDepth();
          }
        }

        public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
        {
          oprot.IncrementRecursionDepth();
          try
          {
            var tmp61 = new TStruct("auth_getGameToken_result");
            await oprot.WriteStructBeginAsync(tmp61, cancellationToken);
            var tmp62 = new TField();

            if(this.__isset.@success)
            {
              if (Success != null)
              {
                tmp62.Name = "Success";
                tmp62.Type = TType.String;
                tmp62.ID = 0;
                await oprot.WriteFieldBeginAsync(tmp62, cancellationToken);
                await oprot.WriteStringAsync(Success, cancellationToken);
                await oprot.WriteFieldEndAsync(cancellationToken);
              }
            }
            await oprot.WriteFieldStopAsync(cancellationToken);
            await oprot.WriteStructEndAsync(cancellationToken);
          }
          finally
          {
            oprot.DecrementRecursionDepth();
          }
        }

        public override bool Equals(object that)
        {
          if (!(that is auth_getGameToken_result other)) return false;
          if (ReferenceEquals(this, other)) return true;
          return ((__isset.@success == other.__isset.@success) && ((!__isset.@success) || (global::System.Object.Equals(Success, other.Success))));
        }

        public override int GetHashCode() {
          int hashcode = 157;
          unchecked {
            if((Success != null) && __isset.@success)
            {
              hashcode = (hashcode * 397) + Success.GetHashCode();
            }
          }
          return hashcode;
        }

        public override string ToString()
        {
          var tmp63 = new StringBuilder("auth_getGameToken_result(");
          int tmp64 = 0;
          if((Success != null) && __isset.@success)
          {
            if(0 < tmp64++) { tmp63.Append(", "); }
            tmp63.Append("Success: ");
            Success.ToString(tmp63);
          }
          tmp63.Append(')');
          return tmp63.ToString();
        }
      }


      public partial class settings_get_args : TBase
      {
        private string _gameSession;
        private string _key;

        public string GameSession
        {
          get
          {
            return _gameSession;
          }
          set
          {
            __isset.gameSession = true;
            this._gameSession = value;
          }
        }

        public string Key
        {
          get
          {
            return _key;
          }
          set
          {
            __isset.@key = true;
            this._key = value;
          }
        }


        public Isset __isset;
        public struct Isset
        {
          public bool gameSession;
          public bool @key;
        }

        public settings_get_args()
        {
        }

        public settings_get_args DeepCopy()
        {
          var tmp65 = new settings_get_args();
          if((GameSession != null) && __isset.gameSession)
          {
            tmp65.GameSession = this.GameSession;
          }
          tmp65.__isset.gameSession = this.__isset.gameSession;
          if((Key != null) && __isset.@key)
          {
            tmp65.Key = this.Key;
          }
          tmp65.__isset.@key = this.__isset.@key;
          return tmp65;
        }

        public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
        {
          iprot.IncrementRecursionDepth();
          try
          {
            TField field;
            await iprot.ReadStructBeginAsync(cancellationToken);
            while (true)
            {
              field = await iprot.ReadFieldBeginAsync(cancellationToken);
              if (field.Type == TType.Stop)
              {
                break;
              }

              switch (field.ID)
              {
                case 1:
                  if (field.Type == TType.String)
                  {
                    GameSession = await iprot.ReadStringAsync(cancellationToken);
                  }
                  else
                  {
                    await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                  }
                  break;
                case 2:
                  if (field.Type == TType.String)
                  {
                    Key = await iprot.ReadStringAsync(cancellationToken);
                  }
                  else
                  {
                    await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                  }
                  break;
                default: 
                  await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                  break;
              }

              await iprot.ReadFieldEndAsync(cancellationToken);
            }

            await iprot.ReadStructEndAsync(cancellationToken);
          }
          finally
          {
            iprot.DecrementRecursionDepth();
          }
        }

        public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
        {
          oprot.IncrementRecursionDepth();
          try
          {
            var tmp66 = new TStruct("settings_get_args");
            await oprot.WriteStructBeginAsync(tmp66, cancellationToken);
            var tmp67 = new TField();
            if((GameSession != null) && __isset.gameSession)
            {
              tmp67.Name = "gameSession";
              tmp67.Type = TType.String;
              tmp67.ID = 1;
              await oprot.WriteFieldBeginAsync(tmp67, cancellationToken);
              await oprot.WriteStringAsync(GameSession, cancellationToken);
              await oprot.WriteFieldEndAsync(cancellationToken);
            }
            if((Key != null) && __isset.@key)
            {
              tmp67.Name = "key";
              tmp67.Type = TType.String;
              tmp67.ID = 2;
              await oprot.WriteFieldBeginAsync(tmp67, cancellationToken);
              await oprot.WriteStringAsync(Key, cancellationToken);
              await oprot.WriteFieldEndAsync(cancellationToken);
            }
            await oprot.WriteFieldStopAsync(cancellationToken);
            await oprot.WriteStructEndAsync(cancellationToken);
          }
          finally
          {
            oprot.DecrementRecursionDepth();
          }
        }

        public override bool Equals(object that)
        {
          if (!(that is settings_get_args other)) return false;
          if (ReferenceEquals(this, other)) return true;
          return ((__isset.gameSession == other.__isset.gameSession) && ((!__isset.gameSession) || (global::System.Object.Equals(GameSession, other.GameSession))))
            && ((__isset.@key == other.__isset.@key) && ((!__isset.@key) || (global::System.Object.Equals(Key, other.Key))));
        }

        public override int GetHashCode() {
          int hashcode = 157;
          unchecked {
            if((GameSession != null) && __isset.gameSession)
            {
              hashcode = (hashcode * 397) + GameSession.GetHashCode();
            }
            if((Key != null) && __isset.@key)
            {
              hashcode = (hashcode * 397) + Key.GetHashCode();
            }
          }
          return hashcode;
        }

        public override string ToString()
        {
          var tmp68 = new StringBuilder("settings_get_args(");
          int tmp69 = 0;
          if((GameSession != null) && __isset.gameSession)
          {
            if(0 < tmp69++) { tmp68.Append(", "); }
            tmp68.Append("GameSession: ");
            GameSession.ToString(tmp68);
          }
          if((Key != null) && __isset.@key)
          {
            if(0 < tmp69++) { tmp68.Append(", "); }
            tmp68.Append("Key: ");
            Key.ToString(tmp68);
          }
          tmp68.Append(')');
          return tmp68.ToString();
        }
      }


      public partial class settings_get_result : TBase
      {
        private string _success;

        public string Success
        {
          get
          {
            return _success;
          }
          set
          {
            __isset.@success = true;
            this._success = value;
          }
        }


        public Isset __isset;
        public struct Isset
        {
          public bool @success;
        }

        public settings_get_result()
        {
        }

        public settings_get_result DeepCopy()
        {
          var tmp70 = new settings_get_result();
          if((Success != null) && __isset.@success)
          {
            tmp70.Success = this.Success;
          }
          tmp70.__isset.@success = this.__isset.@success;
          return tmp70;
        }

        public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
        {
          iprot.IncrementRecursionDepth();
          try
          {
            TField field;
            await iprot.ReadStructBeginAsync(cancellationToken);
            while (true)
            {
              field = await iprot.ReadFieldBeginAsync(cancellationToken);
              if (field.Type == TType.Stop)
              {
                break;
              }

              switch (field.ID)
              {
                case 0:
                  if (field.Type == TType.String)
                  {
                    Success = await iprot.ReadStringAsync(cancellationToken);
                  }
                  else
                  {
                    await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                  }
                  break;
                default: 
                  await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                  break;
              }

              await iprot.ReadFieldEndAsync(cancellationToken);
            }

            await iprot.ReadStructEndAsync(cancellationToken);
          }
          finally
          {
            iprot.DecrementRecursionDepth();
          }
        }

        public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
        {
          oprot.IncrementRecursionDepth();
          try
          {
            var tmp71 = new TStruct("settings_get_result");
            await oprot.WriteStructBeginAsync(tmp71, cancellationToken);
            var tmp72 = new TField();

            if(this.__isset.@success)
            {
              if (Success != null)
              {
                tmp72.Name = "Success";
                tmp72.Type = TType.String;
                tmp72.ID = 0;
                await oprot.WriteFieldBeginAsync(tmp72, cancellationToken);
                await oprot.WriteStringAsync(Success, cancellationToken);
                await oprot.WriteFieldEndAsync(cancellationToken);
              }
            }
            await oprot.WriteFieldStopAsync(cancellationToken);
            await oprot.WriteStructEndAsync(cancellationToken);
          }
          finally
          {
            oprot.DecrementRecursionDepth();
          }
        }

        public override bool Equals(object that)
        {
          if (!(that is settings_get_result other)) return false;
          if (ReferenceEquals(this, other)) return true;
          return ((__isset.@success == other.__isset.@success) && ((!__isset.@success) || (global::System.Object.Equals(Success, other.Success))));
        }

        public override int GetHashCode() {
          int hashcode = 157;
          unchecked {
            if((Success != null) && __isset.@success)
            {
              hashcode = (hashcode * 397) + Success.GetHashCode();
            }
          }
          return hashcode;
        }

        public override string ToString()
        {
          var tmp73 = new StringBuilder("settings_get_result(");
          int tmp74 = 0;
          if((Success != null) && __isset.@success)
          {
            if(0 < tmp74++) { tmp73.Append(", "); }
            tmp73.Append("Success: ");
            Success.ToString(tmp73);
          }
          tmp73.Append(')');
          return tmp73.ToString();
        }
      }


      public partial class userInfo_get_args : TBase
      {
        private string _gameSession;

        public string GameSession
        {
          get
          {
            return _gameSession;
          }
          set
          {
            __isset.gameSession = true;
            this._gameSession = value;
          }
        }


        public Isset __isset;
        public struct Isset
        {
          public bool gameSession;
        }

        public userInfo_get_args()
        {
        }

        public userInfo_get_args DeepCopy()
        {
          var tmp75 = new userInfo_get_args();
          if((GameSession != null) && __isset.gameSession)
          {
            tmp75.GameSession = this.GameSession;
          }
          tmp75.__isset.gameSession = this.__isset.gameSession;
          return tmp75;
        }

        public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
        {
          iprot.IncrementRecursionDepth();
          try
          {
            TField field;
            await iprot.ReadStructBeginAsync(cancellationToken);
            while (true)
            {
              field = await iprot.ReadFieldBeginAsync(cancellationToken);
              if (field.Type == TType.Stop)
              {
                break;
              }

              switch (field.ID)
              {
                case 1:
                  if (field.Type == TType.String)
                  {
                    GameSession = await iprot.ReadStringAsync(cancellationToken);
                  }
                  else
                  {
                    await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                  }
                  break;
                default: 
                  await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                  break;
              }

              await iprot.ReadFieldEndAsync(cancellationToken);
            }

            await iprot.ReadStructEndAsync(cancellationToken);
          }
          finally
          {
            iprot.DecrementRecursionDepth();
          }
        }

        public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
        {
          oprot.IncrementRecursionDepth();
          try
          {
            var tmp76 = new TStruct("userInfo_get_args");
            await oprot.WriteStructBeginAsync(tmp76, cancellationToken);
            var tmp77 = new TField();
            if((GameSession != null) && __isset.gameSession)
            {
              tmp77.Name = "gameSession";
              tmp77.Type = TType.String;
              tmp77.ID = 1;
              await oprot.WriteFieldBeginAsync(tmp77, cancellationToken);
              await oprot.WriteStringAsync(GameSession, cancellationToken);
              await oprot.WriteFieldEndAsync(cancellationToken);
            }
            await oprot.WriteFieldStopAsync(cancellationToken);
            await oprot.WriteStructEndAsync(cancellationToken);
          }
          finally
          {
            oprot.DecrementRecursionDepth();
          }
        }

        public override bool Equals(object that)
        {
          if (!(that is userInfo_get_args other)) return false;
          if (ReferenceEquals(this, other)) return true;
          return ((__isset.gameSession == other.__isset.gameSession) && ((!__isset.gameSession) || (global::System.Object.Equals(GameSession, other.GameSession))));
        }

        public override int GetHashCode() {
          int hashcode = 157;
          unchecked {
            if((GameSession != null) && __isset.gameSession)
            {
              hashcode = (hashcode * 397) + GameSession.GetHashCode();
            }
          }
          return hashcode;
        }

        public override string ToString()
        {
          var tmp78 = new StringBuilder("userInfo_get_args(");
          int tmp79 = 0;
          if((GameSession != null) && __isset.gameSession)
          {
            if(0 < tmp79++) { tmp78.Append(", "); }
            tmp78.Append("GameSession: ");
            GameSession.ToString(tmp78);
          }
          tmp78.Append(')');
          return tmp78.ToString();
        }
      }


      public partial class userInfo_get_result : TBase
      {
        private string _success;

        public string Success
        {
          get
          {
            return _success;
          }
          set
          {
            __isset.@success = true;
            this._success = value;
          }
        }


        public Isset __isset;
        public struct Isset
        {
          public bool @success;
        }

        public userInfo_get_result()
        {
        }

        public userInfo_get_result DeepCopy()
        {
          var tmp80 = new userInfo_get_result();
          if((Success != null) && __isset.@success)
          {
            tmp80.Success = this.Success;
          }
          tmp80.__isset.@success = this.__isset.@success;
          return tmp80;
        }

        public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
        {
          iprot.IncrementRecursionDepth();
          try
          {
            TField field;
            await iprot.ReadStructBeginAsync(cancellationToken);
            while (true)
            {
              field = await iprot.ReadFieldBeginAsync(cancellationToken);
              if (field.Type == TType.Stop)
              {
                break;
              }

              switch (field.ID)
              {
                case 0:
                  if (field.Type == TType.String)
                  {
                    Success = await iprot.ReadStringAsync(cancellationToken);
                  }
                  else
                  {
                    await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                  }
                  break;
                default: 
                  await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                  break;
              }

              await iprot.ReadFieldEndAsync(cancellationToken);
            }

            await iprot.ReadStructEndAsync(cancellationToken);
          }
          finally
          {
            iprot.DecrementRecursionDepth();
          }
        }

        public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
        {
          oprot.IncrementRecursionDepth();
          try
          {
            var tmp81 = new TStruct("userInfo_get_result");
            await oprot.WriteStructBeginAsync(tmp81, cancellationToken);
            var tmp82 = new TField();

            if(this.__isset.@success)
            {
              if (Success != null)
              {
                tmp82.Name = "Success";
                tmp82.Type = TType.String;
                tmp82.ID = 0;
                await oprot.WriteFieldBeginAsync(tmp82, cancellationToken);
                await oprot.WriteStringAsync(Success, cancellationToken);
                await oprot.WriteFieldEndAsync(cancellationToken);
              }
            }
            await oprot.WriteFieldStopAsync(cancellationToken);
            await oprot.WriteStructEndAsync(cancellationToken);
          }
          finally
          {
            oprot.DecrementRecursionDepth();
          }
        }

        public override bool Equals(object that)
        {
          if (!(that is userInfo_get_result other)) return false;
          if (ReferenceEquals(this, other)) return true;
          return ((__isset.@success == other.__isset.@success) && ((!__isset.@success) || (global::System.Object.Equals(Success, other.Success))));
        }

        public override int GetHashCode() {
          int hashcode = 157;
          unchecked {
            if((Success != null) && __isset.@success)
            {
              hashcode = (hashcode * 397) + Success.GetHashCode();
            }
          }
          return hashcode;
        }

        public override string ToString()
        {
          var tmp83 = new StringBuilder("userInfo_get_result(");
          int tmp84 = 0;
          if((Success != null) && __isset.@success)
          {
            if(0 < tmp84++) { tmp83.Append(", "); }
            tmp83.Append("Success: ");
            Success.ToString(tmp83);
          }
          tmp83.Append(')');
          return tmp83.ToString();
        }
      }


      public partial class updater_isUpdateAvailable_args : TBase
      {
        private string _gameSession;

        public string GameSession
        {
          get
          {
            return _gameSession;
          }
          set
          {
            __isset.gameSession = true;
            this._gameSession = value;
          }
        }


        public Isset __isset;
        public struct Isset
        {
          public bool gameSession;
        }

        public updater_isUpdateAvailable_args()
        {
        }

        public updater_isUpdateAvailable_args DeepCopy()
        {
          var tmp85 = new updater_isUpdateAvailable_args();
          if((GameSession != null) && __isset.gameSession)
          {
            tmp85.GameSession = this.GameSession;
          }
          tmp85.__isset.gameSession = this.__isset.gameSession;
          return tmp85;
        }

        public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
        {
          iprot.IncrementRecursionDepth();
          try
          {
            TField field;
            await iprot.ReadStructBeginAsync(cancellationToken);
            while (true)
            {
              field = await iprot.ReadFieldBeginAsync(cancellationToken);
              if (field.Type == TType.Stop)
              {
                break;
              }

              switch (field.ID)
              {
                case 1:
                  if (field.Type == TType.String)
                  {
                    GameSession = await iprot.ReadStringAsync(cancellationToken);
                  }
                  else
                  {
                    await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                  }
                  break;
                default: 
                  await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                  break;
              }

              await iprot.ReadFieldEndAsync(cancellationToken);
            }

            await iprot.ReadStructEndAsync(cancellationToken);
          }
          finally
          {
            iprot.DecrementRecursionDepth();
          }
        }

        public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
        {
          oprot.IncrementRecursionDepth();
          try
          {
            var tmp86 = new TStruct("updater_isUpdateAvailable_args");
            await oprot.WriteStructBeginAsync(tmp86, cancellationToken);
            var tmp87 = new TField();
            if((GameSession != null) && __isset.gameSession)
            {
              tmp87.Name = "gameSession";
              tmp87.Type = TType.String;
              tmp87.ID = 1;
              await oprot.WriteFieldBeginAsync(tmp87, cancellationToken);
              await oprot.WriteStringAsync(GameSession, cancellationToken);
              await oprot.WriteFieldEndAsync(cancellationToken);
            }
            await oprot.WriteFieldStopAsync(cancellationToken);
            await oprot.WriteStructEndAsync(cancellationToken);
          }
          finally
          {
            oprot.DecrementRecursionDepth();
          }
        }

        public override bool Equals(object that)
        {
          if (!(that is updater_isUpdateAvailable_args other)) return false;
          if (ReferenceEquals(this, other)) return true;
          return ((__isset.gameSession == other.__isset.gameSession) && ((!__isset.gameSession) || (global::System.Object.Equals(GameSession, other.GameSession))));
        }

        public override int GetHashCode() {
          int hashcode = 157;
          unchecked {
            if((GameSession != null) && __isset.gameSession)
            {
              hashcode = (hashcode * 397) + GameSession.GetHashCode();
            }
          }
          return hashcode;
        }

        public override string ToString()
        {
          var tmp88 = new StringBuilder("updater_isUpdateAvailable_args(");
          int tmp89 = 0;
          if((GameSession != null) && __isset.gameSession)
          {
            if(0 < tmp89++) { tmp88.Append(", "); }
            tmp88.Append("GameSession: ");
            GameSession.ToString(tmp88);
          }
          tmp88.Append(')');
          return tmp88.ToString();
        }
      }


      public partial class updater_isUpdateAvailable_result : TBase
      {
        private string _success;

        public string Success
        {
          get
          {
            return _success;
          }
          set
          {
            __isset.@success = true;
            this._success = value;
          }
        }


        public Isset __isset;
        public struct Isset
        {
          public bool @success;
        }

        public updater_isUpdateAvailable_result()
        {
        }

        public updater_isUpdateAvailable_result DeepCopy()
        {
          var tmp90 = new updater_isUpdateAvailable_result();
          if((Success != null) && __isset.@success)
          {
            tmp90.Success = this.Success;
          }
          tmp90.__isset.@success = this.__isset.@success;
          return tmp90;
        }

        public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
        {
          iprot.IncrementRecursionDepth();
          try
          {
            TField field;
            await iprot.ReadStructBeginAsync(cancellationToken);
            while (true)
            {
              field = await iprot.ReadFieldBeginAsync(cancellationToken);
              if (field.Type == TType.Stop)
              {
                break;
              }

              switch (field.ID)
              {
                case 0:
                  if (field.Type == TType.String)
                  {
                    Success = await iprot.ReadStringAsync(cancellationToken);
                  }
                  else
                  {
                    await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                  }
                  break;
                default: 
                  await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                  break;
              }

              await iprot.ReadFieldEndAsync(cancellationToken);
            }

            await iprot.ReadStructEndAsync(cancellationToken);
          }
          finally
          {
            iprot.DecrementRecursionDepth();
          }
        }

        public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
        {
          oprot.IncrementRecursionDepth();
          try
          {
            var tmp91 = new TStruct("updater_isUpdateAvailable_result");
            await oprot.WriteStructBeginAsync(tmp91, cancellationToken);
            var tmp92 = new TField();

            if(this.__isset.@success)
            {
              if (Success != null)
              {
                tmp92.Name = "Success";
                tmp92.Type = TType.String;
                tmp92.ID = 0;
                await oprot.WriteFieldBeginAsync(tmp92, cancellationToken);
                await oprot.WriteStringAsync(Success, cancellationToken);
                await oprot.WriteFieldEndAsync(cancellationToken);
              }
            }
            await oprot.WriteFieldStopAsync(cancellationToken);
            await oprot.WriteStructEndAsync(cancellationToken);
          }
          finally
          {
            oprot.DecrementRecursionDepth();
          }
        }

        public override bool Equals(object that)
        {
          if (!(that is updater_isUpdateAvailable_result other)) return false;
          if (ReferenceEquals(this, other)) return true;
          return ((__isset.@success == other.__isset.@success) && ((!__isset.@success) || (global::System.Object.Equals(Success, other.Success))));
        }

        public override int GetHashCode() {
          int hashcode = 157;
          unchecked {
            if((Success != null) && __isset.@success)
            {
              hashcode = (hashcode * 397) + Success.GetHashCode();
            }
          }
          return hashcode;
        }

        public override string ToString()
        {
          var tmp93 = new StringBuilder("updater_isUpdateAvailable_result(");
          int tmp94 = 0;
          if((Success != null) && __isset.@success)
          {
            if(0 < tmp94++) { tmp93.Append(", "); }
            tmp93.Append("Success: ");
            Success.ToString(tmp93);
          }
          tmp93.Append(')');
          return tmp93.ToString();
        }
      }

    }

  }
}
